import React, { useState } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  Image,
  Alert,
  StatusBar,
  TextInput,
  Modal,
  FlatList,
  Dimensions,
} from 'react-native';

const { width } = Dimensions.get('window');

const MOCK_DATA = {
  user: {
    id: '1',
    name: 'Alessandro Ferrari',
    email: 'alex.ferrari@gmail.com',
    avatar: 'https://i.pravatar.cc/150?img=68',
    plan: 'Pro',
    joinDate: 'Membro dal Gen 2024',
    balance: '€2.450,00',
    totalInvested: '€12.800,00',
    totalReturn: '+18,4%',
  },
  notifications: [
    { id: '1', title: 'Dividendo ricevuto', desc: 'Apple Inc. ha pagato €42,30', time: '2m fa', read: false, type: 'success' },
    { id: '2', title: 'Allerta prezzo', desc: 'Tesla TSLA scesa del 3,2%', time: '15m fa', read: false, type: 'warning' },
    { id: '3', title: 'Ordine eseguito', desc: 'Acquisto 5 azioni MSFT completato', time: '1h fa', read: true, type: 'info' },
    { id: '4', title: 'Report mensile', desc: 'Il tuo report di Giugno è pronto', time: '3h fa', read: true, type: 'info' },
  ],
  portfolio: [
    {
      id: '1',
      name: 'Apple Inc.',
      ticker: 'AAPL',
      price: '€189,42',
      change: '+2,34%',
      positive: true,
      shares: 15,
      value: '€2.841,30',
      logo: 'https://logo.clearbit.com/apple.com',
      sector: 'Tecnologia',
      description: 'Apple Inc. progetta, produce e vende smartphone, computer, tablet, indossabili e accessori. È una delle aziende più capitalizzate al mondo con un ecosistema di prodotti e servizi premium.',
      chart: [120, 135, 128, 142, 138, 155, 160, 158, 165, 172, 168, 189],
      pe: '29,4x',
      marketCap: '€2,94T',
      dividend: '0,92%',
      week52: '€164,08 - €199,62',
    },
    {
      id: '2',
      name: 'Microsoft',
      ticker: 'MSFT',
      price: '€415,50',
      change: '+1,12%',
      positive: true,
      shares: 8,
      value: '€3.324,00',
      logo: 'https://logo.clearbit.com/microsoft.com',
      sector: 'Tecnologia',
      description: 'Microsoft Corporation sviluppa e supporta software, servizi, dispositivi e soluzioni. Leader nel cloud computing con Azure e nella produttività con Office 365.',
      chart: [310, 325, 318, 340, 355, 362, 370, 385, 390, 402, 410, 415],
      pe: '36,2x',
      marketCap: '€3,08T',
      dividend: '0,72%',
      week52: '€309,45 - €420,82',
    },
    {
      id: '3',
      name: 'Tesla Inc.',
      ticker: 'TSLA',
      price: '€248,50',
      change: '-3,21%',
      positive: false,
      shares: 10,
      value: '€2.485,00',
      logo: 'https://logo.clearbit.com/tesla.com',